export const BooksList = [
  {
    title: "1 Księga Mojżeszowa",
    value: "1mo",
    isOldTestament: true,
    numberOfChapters: 50,
  },
  {
    title: "2 Księga Mojżeszowa",
    value: "2mo",
    isOldTestament: true,
    numberOfChapters: 40,
  },
  {
    title: "3 Księga Mojżeszowa",
    value: "3mo",
    isOldTestament: true,
    numberOfChapters: 27,
  },
  {
    title: "4 Księga Mojżeszowa",
    value: "4mo",
    isOldTestament: true,
    numberOfChapters: 36,
  },
  {
    title: "5 Księga Mojżeszowa",
    value: "5mo",
    isOldTestament: true,
    isStepAfter: true,
    numberOfChapters: 34,
  },
  {
    title: "Księga Jozuego",
    value: "joz",
    isOldTestament: true,
    numberOfChapters: 24,
  },
  {
    title: "Księga Sędziów",
    value: "sedz",
    isOldTestament: true,
    numberOfChapters: 21,
  },
  {
    title: "Księga Rut",
    value: "rut",
    isOldTestament: true,
    numberOfChapters: 4,
  },
  {
    title: "1 Księga Samuela",
    value: "1sm",
    isOldTestament: true,
    numberOfChapters: 31,
  },
  {
    title: "2 Księga Samuela",
    value: "2sm",
    isOldTestament: true,
    numberOfChapters: 24,
  },
  {
    title: "1 Księga Królewska",
    value: "1krl",
    isOldTestament: true,
    numberOfChapters: 22,
  },
  {
    title: "2 Księga Królewska",
    value: "2krl",
    isOldTestament: true,
    numberOfChapters: 25,
  },
  {
    title: "1 Księga Kronik",
    value: "1krn",
    isOldTestament: true,
    numberOfChapters: 29,
  },
  {
    title: "2 Księga Kronik",
    value: "2krn",
    isOldTestament: true,
    numberOfChapters: 36,
  },
  {
    title: "Księga Ezdrasza",
    value: "ezd",
    isOldTestament: true,
    numberOfChapters: 10,
  },
  {
    title: "Księga Nehemiasza",
    value: "neh",
    isOldTestament: true,
    numberOfChapters: 13,
  },
  {
    title: "Księga Estery",
    value: "est",
    isOldTestament: true,
    numberOfChapters: 10,
  },
  {
    title: "Księga Hioba",
    value: "hiob",
    isOldTestament: true,
    numberOfChapters: 42,
  },
  {
    title: "Księga Psalmów",
    value: "ps",
    isOldTestament: true,
    numberOfChapters: 150,
  },
  {
    title: "Księga Przysłów",
    value: "prz",
    isOldTestament: true,
    numberOfChapters: 31,
  },
  {
    title: "Księga Koheleta",
    value: "koh",
    isOldTestament: true,
    numberOfChapters: 12,
  },
  {
    title: "Pieśń nad Pieśniami",
    value: "pnp",
    isOldTestament: true,
    isStepAfter: true,
    numberOfChapters: 8,
  },
  {
    title: "Księga Izajasza",
    value: "iz",
    isOldTestament: true,
    numberOfChapters: 66,
  },
  {
    title: "Księga Jeremiasza",
    value: "jer",
    isOldTestament: true,
    numberOfChapters: 52,
  },
  {
    title: "Lamentacje Jeremiasza",
    value: "lam",
    isOldTestament: true,
    numberOfChapters: 5,
  },
  {
    title: "Księga Ezechiela",
    value: "ez",
    isOldTestament: true,
    numberOfChapters: 48,
  },
  {
    title: "Księga Daniela",
    value: "dan",
    isOldTestament: true,
    numberOfChapters: 12,
  },
  {
    title: "Księga Ozeasza",
    value: "oz",
    isOldTestament: true,
    numberOfChapters: 14,
  },
  {
    title: "Księga Joela",
    value: "joel",
    isOldTestament: true,
    numberOfChapters: 3,
  },
  {
    title: "Księga Amosa",
    value: "am",
    isOldTestament: true,
    numberOfChapters: 9,
  },
  {
    title: "Księga Abdiasza",
    value: "ab",
    isOldTestament: true,
    numberOfChapters: 1,
  },
  {
    title: "Księga Jonasza",
    value: "jon",
    isOldTestament: true,
    numberOfChapters: 4,
  },
  {
    title: "Księga Micheasza",
    value: "mi",
    isOldTestament: true,
    numberOfChapters: 7,
  },
  {
    title: "Księga Nahuma",
    value: "na",
    isOldTestament: true,
    numberOfChapters: 3,
  },
  {
    title: "Księga Habakuka",
    value: "ha",
    isOldTestament: true,
    numberOfChapters: 3,
  },
  {
    title: "Księga Sofoniasza",
    value: "so",
    isOldTestament: true,
    numberOfChapters: 3,
  },
  {
    title: "Księga Aggeusza",
    value: "ag",
    isOldTestament: true,
    numberOfChapters: 2,
  },
  {
    title: "Księga Zachariasza",
    value: "za",
    isOldTestament: true,
    numberOfChapters: 14,
  },
  {
    title: "Księga Malachiasza",
    value: "ma",
    isOldTestament: true,
    numberOfChapters: 3,
  },
  {
    title: "Ewangelia Mateusza",
    value: "mt",
    isOldTestament: false,
    numberOfChapters: 28,
  },
  {
    title: "Ewangelia Marka",
    value: "mk",
    isOldTestament: false,
    numberOfChapters: 16,
  },
  {
    title: "Ewangelia Łukasza",
    value: "lk",
    isOldTestament: false,
    numberOfChapters: 24,
  },
  {
    title: "Ewangelia Jana",
    value: "j",
    isOldTestament: false,
    numberOfChapters: 21,
  },
  {
    title: "Dzieje Apostolskie",
    value: "dz",
    isOldTestament: false,
    isStepAfter: true,
    numberOfChapters: 28,
  },
  {
    title: "List do Rzymian",
    value: "rzym",
    isOldTestament: false,
    numberOfChapters: 16,
  },
  {
    title: "1 List do Koryntian",
    value: "1kor",
    isOldTestament: false,
    numberOfChapters: 16,
  },
  {
    title: "2 List do Koryntian",
    value: "2kor",
    isOldTestament: false,
    numberOfChapters: 13,
  },
  {
    title: "List do Galatów",
    value: "gal",
    isOldTestament: false,
    numberOfChapters: 6,
  },
  {
    title: "List do Efezjan",
    value: "ef",
    isOldTestament: false,
    numberOfChapters: 6,
  },
  {
    title: "List do Filipian",
    value: "flp",
    isOldTestament: false,
    numberOfChapters: 4,
  },
  {
    title: "List do Kolosan",
    value: "kol",
    isOldTestament: false,
    numberOfChapters: 4,
  },
  {
    title: "1 List do Tesaloniczan",
    value: "1tes",
    isOldTestament: false,
    numberOfChapters: 5,
  },
  {
    title: "2 List do Tesaloniczan",
    value: "2tes",
    isOldTestament: false,
    numberOfChapters: 3,
  },
  {
    title: "1 List do Tymoteusza",
    value: "1tym",
    isOldTestament: false,
    numberOfChapters: 6,
  },
  {
    title: "2 List do Tymoteusza",
    value: "2tym",
    isOldTestament: false,
    numberOfChapters: 4,
  },
  {
    title: "List do Tytusa",
    value: "tyt",
    isOldTestament: false,
    numberOfChapters: 3,
  },
  {
    title: "List do Filemona",
    value: "flm",
    isOldTestament: false,
    numberOfChapters: 1,
  },
  {
    title: "List do Hebrajczyków",
    value: "heb",
    isOldTestament: false,
    numberOfChapters: 13,
  },
  {
    title: "List Jakuba",
    value: "jak",
    isOldTestament: false,
    numberOfChapters: 5,
  },
  {
    title: "1 List Piotra",
    value: "1ptr",
    isOldTestament: false,
    numberOfChapters: 5,
  },
  {
    title: "2 List Piotra",
    value: "2ptr",
    isOldTestament: false,
    numberOfChapters: 3,
  },
  {
    title: "1 List Jana",
    value: "1j",
    isOldTestament: false,
    numberOfChapters: 5,
  },
  {
    title: "2 List Jana",
    value: "2j",
    isOldTestament: false,
    numberOfChapters: 1,
  },
  {
    title: "3 List Jana",
    value: "3j",
    isOldTestament: false,
    numberOfChapters: 1,
  },
  {
    title: "List Judy",
    value: "jud",
    isOldTestament: false,
    numberOfChapters: 1,
  },
  {
    title: "Apokalipsa Jana",
    value: "ap",
    isOldTestament: false,
    numberOfChapters: 22,
  },
];
